
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}  # Cargar desde el archivo .env
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}  # Cargar desde el archivo .env
    ports:
      - "${MONGO_PORT}:27017"  # Usar el puerto desde el archivo .env
    volumes:
      - mongodb_data:/data/db  # Persistencia de los datos
    networks:
      - bloxtek_network  # Asignar a la red personalizada

  backend:
    build: .  
    container_name: express
    ports:
      - "${PORT}:${PORT}"  # Usar el puerto del archivo .env
    env_file:
      - .env  # Cargar las variables de entorno desde el archivo .env
    command: npm run start  # Ejecutar el servidor de Express
    depends_on:
      - mongodb  # Asegurarse de que MongoDB esté disponible antes de iniciar el backend
    networks:
      - bloxtek_network  # Asignar a la misma red personalizada

volumes:
  mongodb_data:
    driver: local  # Persistencia de los datos de MongoDB

networks:
  bloxtek_network:  # Definir la red personalizada
    driver: bridge  # Tipo de red (puede usar bridge por defecto)
